version: "3"
services:

  trakt:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/trakt
      DATASOURCE_USERNAME: trakt
      DATASOURCE_PASSWORD: trakt
    ports:
      - "49080:8080"
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: trakt
      POSTGRES_PASSWORD: trakt
      POSTGRES_DB: trakt
    ports:
      - "49432:5432"
