spring:
  main.banner-mode: "off"

logging:
  level:
    root: WARN

---

spring:
  profiles: dev
  main.banner-mode: console

  datasource:
    url: jdbc:postgresql://localhost:49432/trakt
    username: trakt
    password: trakt

logging:
  level:
    root: INFO

trakt:
  csrf-enabled: false
